title: nord
description: Avram Djordjevic's blog
url: "https://avramdj.github.io"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /:title/
highlighter: rouge

# Plugins
plugins:
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore